name: Close Old Conflicted PRs

on:
  schedule:
    - cron: "0 * * * *" 

jobs:
  close_conflicted_prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Close PRs with merge conflicts older than 3 days
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const now = new Date();
            for (const pr of prs.data) {
              const details = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });

              if (details.data.mergeable === false || details.data.mergeable === null) {
                const createdAt = new Date(pr.created_at);
                const diffDays = (now - createdAt) / (1000 * 60 * 60 * 24);
                if (diffDays > 3) {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: "This PR has merge conflicts and has been open for more than 3 days. It will be automatically closed. Please resolve the conflicts and reopen the PR if you'd like to continue working on it."
                  });
                  
                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    state: 'closed'
                  });
                }
              }
            }
